---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: "{{ logrotate_dependencies }}"
    state: present
    update_cache: true

- name: Setup logrotate scripts
  ansible.builtin.template:
    dest: "/etc/logrotate.d/{{ item.name }}"
    src: script.j2
  loop: "{{ logrotate_scripts }}"
  loop_control:
    label: "{{ item.name }}"
